name = "Atmosphere"
uuid = "2c84d669-3b95-46c3-a358-9a76f739ac9c"
authors = ["René Verbeek"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
